import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";

// import Header from "@/components/layout/Header";
// import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/providers/AuthContext";
import { RequestsProvider } from "@/providers/RequestsContext";
import Providers from "./Providers";
import { ServicesProvider } from "@/providers/ServicesContext";
// import QuoteComponent from "@/components/layout/QuoteComponent";

export const metadata = {
	title: "شرکت خدمات گستر جزائری",
	description: "Generated by @mhmojtaba",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<head>
				<link rel="manifest" href="/dashboard/manifest.json" />

				<meta name="theme-color" content="#1e40af" />
				<meta name="mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta
					name="apple-mobile-web-app-status-bar-style"
					content="black-translucent"
				/>
				<link rel="apple-touch-icon" href="/dashboard/icons/icon-512.png" />

				<script
					dangerouslySetInnerHTML={{
						__html: `
              if ('serviceWorker' in navigator) {
                navigator.serviceWorker.register('/dashboard/sw.js');
              }
            `,
					}}
				/>
			</head>
			<body>
				<Providers>
					<AuthProvider>
						<ServicesProvider>
							<RequestsProvider>
								{/* <Header /> */}
								{/* <QuoteComponent /> */}
								<ToastContainer
									position="top-right"
									autoClose={3000}
									hideProgressBar={false}
									newestOnTop
									closeOnClick={false}
									rtl
									pauseOnFocusLoss
									draggable
									pauseOnHover
									theme="light"
									transition={Bounce}
								/>
								{children}
								{/* <Footer /> */}
							</RequestsProvider>
						</ServicesProvider>
					</AuthProvider>
				</Providers>
			</body>
		</html>
	);
}
