import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/providers/AuthContext";
import { RequestsProvider } from "@/providers/RequestsContext";
import Providers from "./Providers";
import { ServicesProvider } from "@/providers/ServicesContext";

export const metadata = {
  title: "اصفهان سرویس کار",
  description: "Generated by @mhmojtaba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <AuthProvider>
            <ServicesProvider>
              <RequestsProvider>
                <Header />
                <ToastContainer
                  position="top-right"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop
                  closeOnClick={false}
                  rtl
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                  transition={Bounce}
                />
                {children}
                <Footer />
              </RequestsProvider>
            </ServicesProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
